### ISSUE TITLE
new passport api strategy - reverseproxy

### ISSUE THREAD

**Issue by steve-jansen** [jaredhanson/passport-oauth#21]
Hoping you can a new strategy to http://passportjs.org/guide/other-api/

I created a new API strategy for passport called "ReverseProxy" to deal with setups that have a reverse HTTP proxy server sit in front of the app servers to handle authentication.  

I added an entry to https://github.com/jaredhanson/passport/wiki/Strategies#wiki-api

URLs for my package are: 
* https://npmjs.org/package/passport-reverseproxy
* https://github.com/steve-jansen/passport-reverseproxy

This provider could be useful for other corporate environments that use reverse proxies for SSO.

Cheers,
Steve Jansen

**Comment by jaredhanson** [comment]
Moved issue to www.passportjs.org project.
